/**
* Test class for DragAndDrop controller.
*/

@IsTest
public class DragAndDropControllerTest {

    @isTest
    static void getCustomTaskStatusTest() {

        Test.startTest();

        Test.stopTest();


    }

    @isTest
    static void getCustomTaskTest() {

        Test.startTest();

        Test.stopTest();


    }

    @isTest
    static void updateTaskStatusTest() {

        Test.startTest();

        Test.stopTest();


    }
}